[frontends]
[frontends.frontend1]
backend = "backend1"
[frontends.frontend1.routes.test_1]
 rule = "PathPrefix:/"

[backends]
[backends.backend1]
[backends.backend1.servers.server1]
url = "http://localhost:4567/"
